### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by vedatkilic** [ant-design/pro-table#67]
When using English, it is not possible to change text "清空" in table-alert. How can we change that text and it is possible to add new i18n locales?

**Comment by chenshuai2144** [comment]
you can look here

**Comment by fatore** [comment]
@chenshuai2144, is that link broken? I couldn't find any examples there on how to solve this issue.

I've found this in another issue, but I don't think it's a good solution:

```
<IntlProvider value={enUSIntl}>
    <ProTable>
        ...
    />
</IntlProvider>
```

I'm not a JS expert, but I have the impression the real problem is caused by this line where zhCN is hardcoded, instead of using the locale specified in the config file: https://github.com/ant-design/pro-table/blob/4f356079c1642714f78bee886e24dc8c52abdffe/src/component/intlContext/index.tsx#L56
